:seedling: Move Image build to GH runner
metal3-io/mariadb-image pull request #29
Opened 2024-08-26 08:08 UTC by mquhuy

Move container image builds to GH runners, using common image build workflow from project-infra, making workflow much cleaner and maintainable.

This solves many GH workflow<->Jenkins related issues, like false timeouts due scheduling and GH workers do not suffer from random network issues as often.

2024-08-26 08:09 UTC, mquhuy commented
/test metal3-ubuntu-e2e-integration-test-main

2024-08-26 08:21 UTC, mquhuy commented
/cc @kashifest @dtantsur @zaneb

2024-08-26 09:38 UTC, kashifest reviewed
/approve

2024-08-27 05:26 UTC, tuminoid commented
/override metal3-ubuntu-e2e-integration-test-main 
Irrelevant test

2024-08-27 05:26 UTC, tuminoid requested changes

2024-08-27 05:26 UTC, tuminoid commented on .github/workflows/build-images-action.yml
> +    if: github.repository == 'metal3-io/baremetal-operator'
Wrong repo

2024-08-27 05:26 UTC, tuminoid commented on .github/workflows/build-images-action.yml
> +      image-name: 'baremetal-operator'
wrong name

2024-08-27 05:38 UTC, tuminoid approved these changes
/lgtm

2024-08-27 05:38 UTC, tuminoid commented
/override metal3-ubuntu-e2e-integration-test-main
Irrelevant test

2024-08-27 05:38 UTC, tuminoid commented
/cc @elfosardo

2024-09-03 11:52 UTC, merged